import Head from 'next/head'
import Post from "../components/post"
import Bio from "../components/Bio"
import Form from "../components/PostForm"
import styles from '../styles/Home.module.scss'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>First Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.container}>
          <Bio dp="https://pbs.twimg.com/profile_images/1392857407483678720/DFbh5Vcf_400x400.jpg" name="new guy" job="frontend reactjs developer" description="first nextjs convo app" />
        <div className={styles.main}>
          <h1>My Posts</h1>
          <div className={styles.posts}>
            <Post content="testing next components" date="5/28/2021" />
            <Post content="testing next components" date="5/28/2021" />
            <Post content="testing next components" date="5/28/2021" />
            <Post content="testing next components" date="5/28/2021" />
            <Form />
          </div>
        </div>
      </main>
    </div>
  )
}
